#!/bin/bash
IP=$(ifconfig | awk '/inet/ { print $2 }' | egrep -v '^fe|^127|^192|^172|::' | head -1)

if [ ! -x /usr/bin/hugo ]
then
 HUGO_VERSION=0.20.2
 DL_SUFFIX=Linux-64bit
 INNER_SUFFIX=linux_amd64
 wget -P /tmp/ https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_${DL_SUFFIX}.tar.gz
 tar -xvf /tmp/hugo_${HUGO_VERSION}_${DL_SUFFIX}.tar.gz -C /tmp
 sudo mv /tmp/hugo_${HUGO_VERSION}_${INNER_SUFFIX}/hugo_${HUGO_VERSION}_${INNER_SUFFIX} /usr/bin/hugo
 sudo chmod +x /usr/bin/hugo
fi

git submodule update --init
git submodule sync

rm -rf workshops-book/public 
(
hugo serve \
 --port 1314 \
 --source workshops-book \
 --forceSyncStatic \
 --renderToDisk \
 --ignoreCache \
 --canonifyURLs \
 --bind ${IP} \
 --appendPort \
 --baseUrl "http://${IP}/" \
 --logFile hugo.log \
 --verboseLog \
 &
LPID=$!
printf "hugo running as pid %s\n" "${LPID}"
printf "%s\n" "${LPID}" > .hugo.pid
) &
